### ISSUE TITLE
Need a Swift package for iOS frameworks

### ISSUE THREAD

**Issue by jane-le** [CleverTap/clevertap-unity-sdk#22]
I'm trying to integrate CleverTap into my Unity project for the first time and run into this error on XCode 12.x when doing this the readme step: 

> In Xcode, go to your Targets, under your app’s name
> Under General, Navigate to Frameworks, Libraries and Embedded Content, please ensure that CleverTapSDK and SDWebImage frameworks are marked as Embed & Sign

![image](https://user-images.githubusercontent.com/29788614/105950054-ba4ede80-603b-11eb-8e9f-77b6ed56c0be.png)

After doing some research I found this: https://stackoverflow.com/questions/65303304/xcode-12-3-building-for-ios-simulator-but-the-linked-and-embedded-framework-wa which suggests to rebuild the framework as an XFC framework

Could you please create a swift package so I could use it as a package dependancy?: https://help.apple.com/xcode/mac/current/#/dev9cc785f4a

**Comment by Aditi3** [comment]
hi @jane-le 

Allow me some time to re-check the same at my end and I will get back to you with an update shortly.

**Comment by Aditi3** [comment]
@jane-le We've identified the issue and added a fix for the same in our development branch. The release that comes with the fix should be out in a day or two. 

Thank you for reporting to us and sorry for the inconvenience caused.

**Comment by jane-le** [comment]
Thank you so much! 🙏
