### ISSUE TITLE
Unable to Build CleverTap Unity SDK v3.0.0 on Android

### ISSUE THREAD

**Issue by TheKeithWolf** [CleverTap/clevertap-unity-sdk#72]
I'm encountering issues when trying to build the CleverTap Unity SDK v3.0.0 on Android. We're currently using CleverTap SDK v2.4.2 in production and I'm updating to 3.0.0. However, when building the project I receive the following exceptions for both development and release builds

- Could not determine the dependencies of task ':unityLibrary:clevertap-android-wrapper.androidlib:compileDebugAidl'.
- Could not determine the dependencies of task ':unityLibrary:clevertap-android-wrapper.androidlib:compileReleaseAidl'.
 
In an attempt to isolate the issue, I created an empty Unity project, imported the CleverTap SDK v3.0.0, and followed the documentation precisely. However, I encountered the same errors as mentioned above when attempting to build for Android.

Appreciate any assistance or guidance on resolving this issue. Thanks!

**Comment by nzagorchev** [comment]
Hello, 
Can you please let me know the Unity Editor version you are using and any other changes to gradle version, settings etc applied?

Thanks,
Nikola

**Comment by TheKeithWolf** [comment]
I'm using 2021.3.28. To make things easier I zipped and attached the sample project. This has all of the settings we use in our production project excluding the account token and Id which have been removed for security reasons
[CT 3.0.zip](https://github.com/CleverTap/clevertap-unity-sdk/files/14078117/CT.3.0.zip)

**Comment by nzagorchev** [comment]
Thank you for the sample project.
We are working on this and will come back with details on our progress.

**Comment by nzagorchev** [comment]
Hello,

To resolve the issue, please ensure:
- Android target SDK is 33
- Use Gradle version 7.0.1 in `settings.gradle`
- Remove the R8 flag, either in the Unity template or directly in Android Studio

Unity Editor 2021.3 version's default settings use Android SDK target and compile versions set to 31. Main Gradle version is 4.1.1, and the launcher version is 6.7.1. Both the Gradle version and the compile SDK version are incompatible with the core CleverTap Android SDK hence also incompatible with the CleverTap Unity SDK 6.0.0.

**Comment by nzagorchev** [comment]
Hi @TheKeithWolf, were you able to resolve the build issue?
